// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_data_response.proto

package funkypanda.proto;

public final class UserDataResponseProtos {
  private UserDataResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserDataResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:funkypanda.UserDataResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
     */
    boolean hasServerStatus();
    /**
     * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
     */
    funkypanda.proto.ServerStatusProtos.ServerStatus getServerStatus();
    /**
     * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
     */
    funkypanda.proto.ServerStatusProtos.ServerStatusOrBuilder getServerStatusOrBuilder();

    /**
     * <code>optional .funkypanda.UserObject userData = 2;</code>
     */
    boolean hasUserData();
    /**
     * <code>optional .funkypanda.UserObject userData = 2;</code>
     */
    funkypanda.proto.UserObjectProtos.UserObject getUserData();
    /**
     * <code>optional .funkypanda.UserObject userData = 2;</code>
     */
    funkypanda.proto.UserObjectProtos.UserObjectOrBuilder getUserDataOrBuilder();
  }
  /**
   * Protobuf type {@code funkypanda.UserDataResponse}
   */
  public static final class UserDataResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:funkypanda.UserDataResponse)
      UserDataResponseOrBuilder {
    // Use UserDataResponse.newBuilder() to construct.
    private UserDataResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserDataResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserDataResponse defaultInstance;
    public static UserDataResponse getDefaultInstance() {
      return defaultInstance;
    }

    public UserDataResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserDataResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              funkypanda.proto.ServerStatusProtos.ServerStatus.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = serverStatus_.toBuilder();
              }
              serverStatus_ = input.readMessage(funkypanda.proto.ServerStatusProtos.ServerStatus.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serverStatus_);
                serverStatus_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              funkypanda.proto.UserObjectProtos.UserObject.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = userData_.toBuilder();
              }
              userData_ = input.readMessage(funkypanda.proto.UserObjectProtos.UserObject.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userData_);
                userData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return funkypanda.proto.UserDataResponseProtos.internal_static_funkypanda_UserDataResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return funkypanda.proto.UserDataResponseProtos.internal_static_funkypanda_UserDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              funkypanda.proto.UserDataResponseProtos.UserDataResponse.class, funkypanda.proto.UserDataResponseProtos.UserDataResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<UserDataResponse> PARSER =
        new com.google.protobuf.AbstractParser<UserDataResponse>() {
      public UserDataResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserDataResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserDataResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERSTATUS_FIELD_NUMBER = 1;
    private funkypanda.proto.ServerStatusProtos.ServerStatus serverStatus_;
    /**
     * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
     */
    public boolean hasServerStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
     */
    public funkypanda.proto.ServerStatusProtos.ServerStatus getServerStatus() {
      return serverStatus_;
    }
    /**
     * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
     */
    public funkypanda.proto.ServerStatusProtos.ServerStatusOrBuilder getServerStatusOrBuilder() {
      return serverStatus_;
    }

    public static final int USERDATA_FIELD_NUMBER = 2;
    private funkypanda.proto.UserObjectProtos.UserObject userData_;
    /**
     * <code>optional .funkypanda.UserObject userData = 2;</code>
     */
    public boolean hasUserData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .funkypanda.UserObject userData = 2;</code>
     */
    public funkypanda.proto.UserObjectProtos.UserObject getUserData() {
      return userData_;
    }
    /**
     * <code>optional .funkypanda.UserObject userData = 2;</code>
     */
    public funkypanda.proto.UserObjectProtos.UserObjectOrBuilder getUserDataOrBuilder() {
      return userData_;
    }

    private void initFields() {
      serverStatus_ = funkypanda.proto.ServerStatusProtos.ServerStatus.getDefaultInstance();
      userData_ = funkypanda.proto.UserObjectProtos.UserObject.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getServerStatus().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasUserData()) {
        if (!getUserData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, serverStatus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, userData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, serverStatus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, userData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static funkypanda.proto.UserDataResponseProtos.UserDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(funkypanda.proto.UserDataResponseProtos.UserDataResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code funkypanda.UserDataResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:funkypanda.UserDataResponse)
        funkypanda.proto.UserDataResponseProtos.UserDataResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return funkypanda.proto.UserDataResponseProtos.internal_static_funkypanda_UserDataResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return funkypanda.proto.UserDataResponseProtos.internal_static_funkypanda_UserDataResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                funkypanda.proto.UserDataResponseProtos.UserDataResponse.class, funkypanda.proto.UserDataResponseProtos.UserDataResponse.Builder.class);
      }

      // Construct using funkypanda.proto.UserDataResponseProtos.UserDataResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServerStatusFieldBuilder();
          getUserDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (serverStatusBuilder_ == null) {
          serverStatus_ = funkypanda.proto.ServerStatusProtos.ServerStatus.getDefaultInstance();
        } else {
          serverStatusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (userDataBuilder_ == null) {
          userData_ = funkypanda.proto.UserObjectProtos.UserObject.getDefaultInstance();
        } else {
          userDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return funkypanda.proto.UserDataResponseProtos.internal_static_funkypanda_UserDataResponse_descriptor;
      }

      public funkypanda.proto.UserDataResponseProtos.UserDataResponse getDefaultInstanceForType() {
        return funkypanda.proto.UserDataResponseProtos.UserDataResponse.getDefaultInstance();
      }

      public funkypanda.proto.UserDataResponseProtos.UserDataResponse build() {
        funkypanda.proto.UserDataResponseProtos.UserDataResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public funkypanda.proto.UserDataResponseProtos.UserDataResponse buildPartial() {
        funkypanda.proto.UserDataResponseProtos.UserDataResponse result = new funkypanda.proto.UserDataResponseProtos.UserDataResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (serverStatusBuilder_ == null) {
          result.serverStatus_ = serverStatus_;
        } else {
          result.serverStatus_ = serverStatusBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (userDataBuilder_ == null) {
          result.userData_ = userData_;
        } else {
          result.userData_ = userDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof funkypanda.proto.UserDataResponseProtos.UserDataResponse) {
          return mergeFrom((funkypanda.proto.UserDataResponseProtos.UserDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(funkypanda.proto.UserDataResponseProtos.UserDataResponse other) {
        if (other == funkypanda.proto.UserDataResponseProtos.UserDataResponse.getDefaultInstance()) return this;
        if (other.hasServerStatus()) {
          mergeServerStatus(other.getServerStatus());
        }
        if (other.hasUserData()) {
          mergeUserData(other.getUserData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerStatus()) {
          
          return false;
        }
        if (!getServerStatus().isInitialized()) {
          
          return false;
        }
        if (hasUserData()) {
          if (!getUserData().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        funkypanda.proto.UserDataResponseProtos.UserDataResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (funkypanda.proto.UserDataResponseProtos.UserDataResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private funkypanda.proto.ServerStatusProtos.ServerStatus serverStatus_ = funkypanda.proto.ServerStatusProtos.ServerStatus.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          funkypanda.proto.ServerStatusProtos.ServerStatus, funkypanda.proto.ServerStatusProtos.ServerStatus.Builder, funkypanda.proto.ServerStatusProtos.ServerStatusOrBuilder> serverStatusBuilder_;
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      public boolean hasServerStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      public funkypanda.proto.ServerStatusProtos.ServerStatus getServerStatus() {
        if (serverStatusBuilder_ == null) {
          return serverStatus_;
        } else {
          return serverStatusBuilder_.getMessage();
        }
      }
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      public Builder setServerStatus(funkypanda.proto.ServerStatusProtos.ServerStatus value) {
        if (serverStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverStatus_ = value;
          onChanged();
        } else {
          serverStatusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      public Builder setServerStatus(
          funkypanda.proto.ServerStatusProtos.ServerStatus.Builder builderForValue) {
        if (serverStatusBuilder_ == null) {
          serverStatus_ = builderForValue.build();
          onChanged();
        } else {
          serverStatusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      public Builder mergeServerStatus(funkypanda.proto.ServerStatusProtos.ServerStatus value) {
        if (serverStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              serverStatus_ != funkypanda.proto.ServerStatusProtos.ServerStatus.getDefaultInstance()) {
            serverStatus_ =
              funkypanda.proto.ServerStatusProtos.ServerStatus.newBuilder(serverStatus_).mergeFrom(value).buildPartial();
          } else {
            serverStatus_ = value;
          }
          onChanged();
        } else {
          serverStatusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      public Builder clearServerStatus() {
        if (serverStatusBuilder_ == null) {
          serverStatus_ = funkypanda.proto.ServerStatusProtos.ServerStatus.getDefaultInstance();
          onChanged();
        } else {
          serverStatusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      public funkypanda.proto.ServerStatusProtos.ServerStatus.Builder getServerStatusBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getServerStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      public funkypanda.proto.ServerStatusProtos.ServerStatusOrBuilder getServerStatusOrBuilder() {
        if (serverStatusBuilder_ != null) {
          return serverStatusBuilder_.getMessageOrBuilder();
        } else {
          return serverStatus_;
        }
      }
      /**
       * <code>required .funkypanda.ServerStatus serverStatus = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          funkypanda.proto.ServerStatusProtos.ServerStatus, funkypanda.proto.ServerStatusProtos.ServerStatus.Builder, funkypanda.proto.ServerStatusProtos.ServerStatusOrBuilder> 
          getServerStatusFieldBuilder() {
        if (serverStatusBuilder_ == null) {
          serverStatusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              funkypanda.proto.ServerStatusProtos.ServerStatus, funkypanda.proto.ServerStatusProtos.ServerStatus.Builder, funkypanda.proto.ServerStatusProtos.ServerStatusOrBuilder>(
                  getServerStatus(),
                  getParentForChildren(),
                  isClean());
          serverStatus_ = null;
        }
        return serverStatusBuilder_;
      }

      private funkypanda.proto.UserObjectProtos.UserObject userData_ = funkypanda.proto.UserObjectProtos.UserObject.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          funkypanda.proto.UserObjectProtos.UserObject, funkypanda.proto.UserObjectProtos.UserObject.Builder, funkypanda.proto.UserObjectProtos.UserObjectOrBuilder> userDataBuilder_;
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      public boolean hasUserData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      public funkypanda.proto.UserObjectProtos.UserObject getUserData() {
        if (userDataBuilder_ == null) {
          return userData_;
        } else {
          return userDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      public Builder setUserData(funkypanda.proto.UserObjectProtos.UserObject value) {
        if (userDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userData_ = value;
          onChanged();
        } else {
          userDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      public Builder setUserData(
          funkypanda.proto.UserObjectProtos.UserObject.Builder builderForValue) {
        if (userDataBuilder_ == null) {
          userData_ = builderForValue.build();
          onChanged();
        } else {
          userDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      public Builder mergeUserData(funkypanda.proto.UserObjectProtos.UserObject value) {
        if (userDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              userData_ != funkypanda.proto.UserObjectProtos.UserObject.getDefaultInstance()) {
            userData_ =
              funkypanda.proto.UserObjectProtos.UserObject.newBuilder(userData_).mergeFrom(value).buildPartial();
          } else {
            userData_ = value;
          }
          onChanged();
        } else {
          userDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      public Builder clearUserData() {
        if (userDataBuilder_ == null) {
          userData_ = funkypanda.proto.UserObjectProtos.UserObject.getDefaultInstance();
          onChanged();
        } else {
          userDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      public funkypanda.proto.UserObjectProtos.UserObject.Builder getUserDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUserDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      public funkypanda.proto.UserObjectProtos.UserObjectOrBuilder getUserDataOrBuilder() {
        if (userDataBuilder_ != null) {
          return userDataBuilder_.getMessageOrBuilder();
        } else {
          return userData_;
        }
      }
      /**
       * <code>optional .funkypanda.UserObject userData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          funkypanda.proto.UserObjectProtos.UserObject, funkypanda.proto.UserObjectProtos.UserObject.Builder, funkypanda.proto.UserObjectProtos.UserObjectOrBuilder> 
          getUserDataFieldBuilder() {
        if (userDataBuilder_ == null) {
          userDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              funkypanda.proto.UserObjectProtos.UserObject, funkypanda.proto.UserObjectProtos.UserObject.Builder, funkypanda.proto.UserObjectProtos.UserObjectOrBuilder>(
                  getUserData(),
                  getParentForChildren(),
                  isClean());
          userData_ = null;
        }
        return userDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:funkypanda.UserDataResponse)
    }

    static {
      defaultInstance = new UserDataResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:funkypanda.UserDataResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_funkypanda_UserDataResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_funkypanda_UserDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030user_data_response.proto\022\nfunkypanda\032\023" +
      "server_status.proto\032\021user_object.proto\"l" +
      "\n\020UserDataResponse\022.\n\014serverStatus\030\001 \002(\013" +
      "2\030.funkypanda.ServerStatus\022(\n\010userData\030\002" +
      " \001(\0132\026.funkypanda.UserObjectB*\n\020funkypan" +
      "da.protoB\026UserDataResponseProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          funkypanda.proto.ServerStatusProtos.getDescriptor(),
          funkypanda.proto.UserObjectProtos.getDescriptor(),
        }, assigner);
    internal_static_funkypanda_UserDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_funkypanda_UserDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_funkypanda_UserDataResponse_descriptor,
        new java.lang.String[] { "ServerStatus", "UserData", });
    funkypanda.proto.ServerStatusProtos.getDescriptor();
    funkypanda.proto.UserObjectProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
